### ISSUE TITLE
Team[33]-Review: LO_Impact and Speed Benchmark Verifiable Requirement

### ISSUE THREAD

**Issue by NpEric360** [Dorps/aiboardgame#10]
Great project idea. 

1. As stated in the rubric, society should be identified as a stakeholder in the project.
2. Verifiable Requirement: The speed benchmark of 5 minutes is referenced in NFR5: A single simulation should not take longer than 5 minutes. It would be more meaningful/verifiable if you specified what type of hardware will be used to determine this benchmark. 

Please create a label for Team 33.

**Comment by michaelilao** [comment]
Addressed in rev1
