### ISSUE TITLE
Team 1 Review: Appendix and Document Links

### ISSUE THREAD

**Issue by JonHaiMcMaster** [Dorps/aiboardgame#100]
It appears that there are no other links in the MG document that lead to the other documentation generated throughout the course. Also, the appendix appears to be missing details regarding the specific system specifications and design (list of libraries used, linters and other technology used, etc.)

Team 1 TA: @NickCapstone

**Comment by EngandDeveloper** [comment]
Thank you for the feedback. The references to other documents were mentioned when appropriate but there is no hyperlinks available. Though, the folder structure is described in README file in our repository and should be easy to follow. We have generated the design doc in a way that it is blind to specific implementation details such as the programming language, libraries and technology used to allow anyone who wants to implement it to use their favourite tech tools. We will take your feedback into consideration and improve our document.

**Comment by michaelilao** [comment]
fixed with rev1
