### ISSUE TITLE
Team[33]-Review: Designing for Open Source and General Use

### ISSUE THREAD

**Issue by M4nd0C4lrissian** [Dorps/aiboardgame#11]
Hey, great project idea for the record - super cool stuff. My SRS feedback has to do with how you might mold your requirements further around generalization, as your docs mentioned that one of your goals down the line is to have this be open-source software to be used by any game-dev with an applicable game. I know that this was more of a stretch-goal, but it's important to keep these goals in mind while designing, so that it's easier to shoot for those goals later down the line. 

My first note is small, but I thought that other prospective game puzzle / strategy / board game devs might be listed as tertiary stakeholders, as they stand to gain from the success of this product. 

My second note is in regard to Figure 2, the "FSM" showing how the game states will be considered. When designing for a generalized board game, it's important to consider all options - like the game ending in a draw. This is very common, like a stalemate in chess, and would render Figure 2 into something that doesn't align with the definition of an FSM, given that it wouldn't guarantee termination in a final state. This may have been an oversight.

My final note relates to the constraint of each simulation taking 5 minutes, thus motivating the choice of resetting the simulations when an error or invalid state is reached. For your purposes, I believe this constraint is not sufficient, for the same reason of generalization as my other two points. The TOTAL simulation time (with repeated simulations), is a function of two properties; the complexity of the game being integrated with and the computation time for updating the predictive model of the AI – the former is dependent on the game that your software integrates with while the latter is independent and controlled by the results of your programming. Due to the nature of dependence on the game, this requires either further constraints or a change for this constraint to be more focused on the AI computation time. 

Anyways I think you guys did a great job overall with your project and requirements so far and I look forward to seeing where it goes.

I think I'm supposed to tag the TA? Idk but @CSchank 

Note: Please create a label for Team[33]-Review

**Comment by michaelilao** [comment]
addressed in Rev1 winning changed to game completing moves, each simulation has a max limit of 5 minutes, if it can complete in less than it will be able to learn faster, but if it overshoots this limit it would not be efficient enough to train on a large scale
