### ISSUE TITLE
Team[33]-Review: Stakeholders & Undesired event handling 

### ISSUE THREAD

**Issue by choueibm** [Dorps/aiboardgame#12]
I really enjoyed reading about your project, it sounds like it will be a very interesting development. 

In your identification of stakeholders, I noticed that "game designers" were not listed. Though, it seemed this was a primary target audience. Users should be considered as stakeholders, as they are impacted by your project.

Another thing I wanted to point out was potentially some unclarity in the way the data visualizer acquires the logs from the game engine and AI agent. As I understood it, the data visualizer is simply responsible for creating visuals portraying the data provided by the game engine and AI agent. Thus, in the case of an undesired event, does restarting the simulation opposed to handling the undesired event completely wipe the existing logs for that simulation? Do the logs containing the data only get passed on upon successful completion of a simulation? Is there a possibility of corrupt or incomplete data from an undesired event being recorded that could possibly impact the accuracy of your AI algorithm? Possibly clarifying how restarting a simulation would potentially correct any undesired states can further demonstrate why that would be the optimal course of action in comparison to event handling. 

All in all, the SRS was effectively and efficiently done. I look forward to seeing the finished product as this is a really interesting idea.

@CSchank

**Comment by michaelilao** [comment]
Addressed in Rev1
