### ISSUE TITLE
Review-VnVReport-Team30 [6 Changes Due to Testing]

### ISSUE THREAD

**Issue by seddikia0** [Dorps/aiboardgame#128]
In section 6: Changes Due to Testing, several points mentioned were regarding how the testing process itself was altered, rather than how the VnV process impacted the quality of the project. 

The rubric mentions the following: "The impact of the VnV process on the quality of the project is clear.  The document clearly shows what changes/improvements were made to the project in response to verification data."

**Comment by EngandDeveloper** [comment]
This issue has been fixed with the Final document revision. Thank you so much for the valuable feedback!
