### ISSUE TITLE
Review-VnVReport-Team30 - Naming of tests

### ISSUE THREAD

**Issue by edwin-do** [Dorps/aiboardgame#130]
Naming tests FR Test 1, FR Test 2 isn't very descriptive to what the test is testing. 

- It may be better to name tests to something more meaningful (i.e. performance, usability or AI state, game board state) so that it is easier to understand and trace to each test

**Comment by EngandDeveloper** [comment]
Naming convention was selected for a better traceability and short names to easy referring purposes. But a descriptive title can be added. Thank you for your feedback.
