### ISSUE TITLE
Team 2 Review

### ISSUE THREAD

**Issue by yuvrajrr** [Dorps/aiboardgame#21]
Great work! The one thing I would suggest is being a bit more detailed on the control of the tests. For example, instead of stating automatic and manual you can go into further detail such as dynamic testing, static testing, functional testing, etc. This will make it easier during the actual testing to determine the best method of testing various FRs and NFRs.

**Comment by Dorps** [comment]
Will add more details on the concrete testing of tic-tac-toe for the VnV plan
