### ISSUE TITLE
Team 2 Review: metrics for better testing goals

### ISSUE THREAD

**Issue by Wililee** [Dorps/aiboardgame#22]
Awesome Job on the VnV plan

One recommendation would be to add metrics or goals for some of the tests

For example in the non-functional tests there is a statement about learning:

https://github.com/Dorps/aiboardgame/blob/0a323144320f57c4ca425180c74ed6a8f7cbbe53/docs/VnVPlan/VnVPlan.tex#L485-L487

Here you state that the win rate should increase from an untrained model after 1000 runs. However it might be good to put a 50/90 bound on this or else this statement becomes very generic. You should also be prepared for the case where the winrate does not change at all / requiring more training.

**Comment by jeff-dang** [comment]
Closed with final revision, can consider this that when failure occurs on the test and adjustment will be made then
