### ISSUE TITLE
Team 2 Review - NFR Test 2

### ISSUE THREAD

**Issue by bentvelj** [Dorps/aiboardgame#23]
Nice VnV plan, just some small points

For NFR Test 2, I don't think having a time limit for explaining the system is the best metric of learnability, since everyone  explains at different rates, has different conversation styles, ways of teaching, etc. I think a more concrete way would be to write a tutorial section that the participant reads (in their chosen language), so that everyone gets the exact same instructions which they can take time to understand at their own pace.

Also, it would be easier to read the VnV if there was a "topic" for each NFR test, to indicate exactly what the NFR test is for. For example, NFR Test 2 seems to be testing Learnability, but that's only through inferring based on how the test will be performed. While you could cross reference the NFRs in the SRS for each test, it would be much easier to get an idea for what each NFR is testing, similar to the Test Derivation for FRs.

Also, "user should be able to run the simulation by him _or herself_"

**Comment by jeff-dang** [comment]
Closed with the inclusion of the final revision
