### ISSUE TITLE
Team 2 Review: Missing NFR Testing Roles

### ISSUE THREAD

**Issue by BasselR** [Dorps/aiboardgame#24]
In the Plan section of your VNV Plan document, you designate roles for the verification of functional requirements of all three of your system's subsystems.
The responsibility of verifying the subsystems' non-functional requirements doesn't seem to be assigned, despite the VNV Plan detailing tests for NFRs along with how they will be performed.
I think there should be atleast one member listed in the Verification and Validation Team section who is responsible for verifying NFRs.

Great job otherwise, the document and its sections are very clear.

**Comment by jeff-dang** [comment]
Added with explanation of supervisor verification
