### ISSUE TITLE
Team 2 Review - Verification and Validation Plan Verification Plan

### ISSUE THREAD

**Issue by MatthewWMcC** [Dorps/aiboardgame#25]
Great work on the VnV plan Document. It was well laid out and included great detail. The only section that seemed to lack some necessary detail to me was the Verification and Validation Plan (section 4.4). In this section you state that "Each team member will review
the V&V Plan and validate each test case and the rest of the document." In this section it might be nice to include that criteria that your group members will use when validating the V&V Plan document. Any more detail for this section to remove the generic language used here would be great.

**Comment by jeff-dang** [comment]
Closed with inclusion of specific tic-tac-toe requirements
