### ISSUE TITLE
Review-SRS-Team4: Document should be organized so that terms and acronyms are defined before use

### ISSUE THREAD

**Issue by vankraa** [Dorps/aiboardgame#3]
Section 1.5.1 contains the terms and definitions that are important for a clear understanding of the document.
Specifically, the term Game Engine appears in section 1.2, before it is defined.

Furthermore, there is an ambiguity of terms stemming from the the definition of "Game Designer" in section 1.5.1, and the use of "software developer" in section 1.1 and "game developers" in Section 1.2. They seem like they are used interchangeably, so should those terms be added to the definition of "Game Designer?"

**Comment by Dorps** [comment]
moved the definitions over the beginning to make better flow of the document
