### ISSUE TITLE
Review-SRS-Team4:  Game Engine variables lack context within the entire system. 

### ISSUE THREAD

**Issue by jtgc1** [Dorps/aiboardgame#4]
Section 2.1 Begins with a great high-level overview of the interactions of the sub-systems. It was easy to follow and made the core concepts of the system clear. 
When you jump to the variables of inside the game engine sub-system, the context with the system is lost. Where are these variables coming from? It would be nice to mention if they are inputs, outputs or internally calculated. Since you decided to go into the specifics of variables, I think you should define them formally. This would include units, proper variable names, etc... 
Finally, I found the next jump the most jarring. You define a state machine that only includes one of the variables that you just defined. As well, there are variables q_1, and q_2 that you never defined. It would be nice if you included some detail and more of the variables such as delta in the finite state machine to connect the two areas. 
Overall, loved the project idea though! Super cool idea and I look forward to seeing the final result.

**Comment by Dorps** [comment]
The variables describe a generalized system applicable to all board games thats why these variabes are generalized, but the extra detailed variables are a good point and have been described in the state machine.
