### ISSUE TITLE
Review-SRS-Team4: Stakeholders Should Include Society

### ISSUE THREAD

**Issue by aujlaa4** [Dorps/aiboardgame#5]
Great work on the project. I have one suggestion regarding stakeholders. The list of stakeholders can be expanded to include a wider range of people. Society isn't listed as a stakeholder of this product event though it should be one as per the rubric. How would this product affect those who are interested in game development? How would it potentially affect consumers of the games that were analyzed using this product? These are all things to think about when brainstorming the stakeholders.
Overall great job! The project idea is very innovative and I am excited to see the end result. Good luck!

**Comment by michaelilao** [comment]
address in rev 1
