### ISSUE TITLE
Review-SRS-Team4: Lack of project-related NFR requirements

### ISSUE THREAD

**Issue by RupinderN** [Dorps/aiboardgame#6]
Great job guys! You guys did a great job making your NFRs verifiable, as using non-verifiable requirements prevents the SRS from being a stand alone document instead of referring to your VnV plan. However, not all the NFRs need to be quantitative, and I believe you can definitely expand on sections you left blank in the context of your project and what it does. An example of this could be expanding the 'Security' section of your NFRs with a possible 'Privacy' requirement stating whether or not your visualization tool will store user data, or an 'Access' requirement regarding who is able to modify your system, or an 'Audit' requirement regarding how your requirements should be easy to follow and verify against both the system and the VnV plan in order to facilitate regular inspections.

Overall, the project sounds very exciting!

**Comment by michaelilao** [comment]
Addressed in rev 1
