### ISSUE TITLE
Requirements should use absolute terms/wording

### ISSUE THREAD

**Issue by celsj** [Dorps/aiboardgame#7]
The requirements seem to cover the project very well, and are clear on priority and function. However requirements, especially functional requirements, are meant to be absolute. Wording like "should" and "can" imply that if the requirements are not met, the application is still correct. This is not the case, and as such all requirements should be worded as "will", "shall", "must", etc. I noticed this specifically on the following requirements: FR1, FR2, FR3, FR4, NFR1, NFR2, NFR3, NFR4, NFR5, NFR6, and NFR7.

Very cool project! I hope to see it in action once it's complete.

**Comment by michaelilao** [comment]
addressed in rev 1
