### ISSUE TITLE
Team[33]-Review: Ambiguous Phase-in Plan 

### ISSUE THREAD

**Issue by MoGwappo** [Dorps/aiboardgame#9]
Phase-In Plan section is ambiguous and merely based on deliverable dates as well as priority. It would be more effective to highlight the subsections within the priorities in which the order of these requirements will be completed (i.e. although a plethora of requirements labeled as high priority must be completed before your listed date, a lot of those requirements must be completed in some orderly fashion). It would be best practice to state the order of which those requirements would be completed in, in order to narrow down your tasks list.

Note: Please create a label for Team[33]-Review

**Comment by michaelilao** [comment]
Addressed in rev1
