### ISSUE TITLE
Team 1 Review: Section 5: Project Overview Vague

### ISSUE THREAD

**Issue by JonHaiMcMaster** [Dorps/aiboardgame#98]
The project overview is intended to be a thorough walk through of the project; including detailed information that describes the value of the project, the problem it is intended to solve, and the goals hoped to be achieved. The project overview in section 5 of the module guide seems more like a description of the scope of the project. In addition, the system context diagram is difficult to interpret, as few details are offered about its components.

Team 1 TA: @NickCapstone

**Comment by michaelilao** [comment]
fixed with rev1
