### ISSUE TITLE
Team 1 Review: Variables and Constants

### ISSUE THREAD

**Issue by JonHaiMcMaster** [Dorps/aiboardgame#99]
No specific monitored or controlled variables are stated. This section is intended to give a list and rationale regarding the specific monitored and controlled variables of the system. In addition, it is not common for there to be a complete lack of constants in this project. This may not be an issue, but it might be a good idea to double check.

Team 1 TA: @NickCapstone

**Comment by michaelilao** [comment]
fixed with rev1
